### ISSUE TITLE
Cannot get MultiMeshInstance to generate

### ISSUE THREAD

**Issue by Arnklit** [Emin981/EminMultiMesh#2]
Hi I've been trying to use this tool, but nothing happens when I try to draw in the viewport after I've added a mesh. Do you have a video of how this is supposed to work? It seems like my selected mesh stops being highlighted the moment I move the mouse cursor over to the 3d viewport. I assume I'm doing something wrong.

![image](https://user-images.githubusercontent.com/4955051/93974921-79357d80-fd6e-11ea-99cf-07761e2ce667.png)

**Comment by Emin981** [comment]
Hi for use the tool you must have an terrain with physics body and collisionshape , bye! :D

Il mer 23 set 2020, 08:29 Kasper Arnklit Frandsen <notifications@github.com>
ha scritto:
