### ISSUE TITLE
Instructions are incorrect

### ISSUE THREAD

**Issue by JustYourAverageJosh** [Emin981/EminMultiMesh#3]
Hi, thank you for this, I hope you keep improving upon it!

I was having an issue getting this to work, and found out it's because the instructions were incorrect. 

For step 1 it says:
"Open new scene and insert a MeshInstance that must have a collision shape."

It should say:
"Open new scene and insert a PhysicsBody (StaticBody) that must have a collision shape."

Also, it should be noted that you can only add a mesh when you click on the collision shape. For example, step 6 could say:

"Step 6. Draw on 3d viewport by clicking left mouse anywhere on the CollisionShape."

Thank you for making this!

**Comment by Emin981** [comment]
Thank you, I will correct this

Il gio 19 nov 2020, 20:14 JustYourAverageJosh <notifications@github.com> ha
scritto:
